#!/bin/sh
set -e


# Parche para establecer un id de usuario si se pasa por variable de entorno
PHP_FPM_CONF=/usr/local/etc/php-fpm.d/www.conf
PHP_FPM_EXISTING_USER=$(awk -v FS="user = " 'NF>1{print $2}' $PHP_FPM_CONF)
if [ "$PHP_FPM_EXISTING_USER" != "" ] \
   && [ "$PHP_FPM_EXISTING_USER" != "www-data" ]; then
   	PHPFPMUSERNAME=$PHP_FPM_EXISTING_USER
else
   PHPFPMUSERNAME=fpmusr$PHPFPMUSERID
fi
if [ "${PHPFPMUSERID}" ]; then
  if [ "$(grep ${PHPFPMUSERNAME} /etc/passwd)" == "" ]; then
     adduser -s /bin/false -H -D -u ${PHPFPMUSERID} -G www-data ${PHPFPMUSERNAME}
     sed -i \
         -e "s/user = www-data/user = ${PHPFPMUSERNAME}/g" \
         $PHP_FPM_CONF
  fi
fi

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
        set -- php-fpm "$@"
fi

exec "$@"

